"""Участки, версии планов, кэш координат, сохранённые дни

Revision ID: f1a5f6e4fd11
Revises: 
Create Date: 2026-09-17 15:25:55.798309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a5f6e4fd11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_key', sa.String(length=512), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_key', name='uq_geo_address')
    )
    op.create_index(op.f('ix_geo_points_address_key'), 'geo_points', ['address_key'], unique=False)
    op.create_index(op.f('ix_geo_points_deleted_at'), 'geo_points', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_geo_points_owner_id'), 'geo_points', ['owner_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('office_address', sa.Text(), nullable=False),
    sa.Column('office_lat', sa.Float(), nullable=False),
    sa.Column('office_lon', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'key', name='uq_region_key')
    )
    op.create_index(op.f('ix_regions_deleted_at'), 'regions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_regions_key'), 'regions', ['key'], unique=False)
    op.create_index(op.f('ix_regions_owner_id'), 'regions', ['owner_id'], unique=False)
    op.create_table('saved_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'region_key', 'name', name='uq_saved_day')
    )
    op.create_index(op.f('ix_saved_days_deleted_at'), 'saved_days', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_saved_days_owner_id'), 'saved_days', ['owner_id'], unique=False)
    op.create_index(op.f('ix_saved_days_region_key'), 'saved_days', ['region_key'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('solver_status', sa.String(length=64), nullable=False),
    sa.Column('solve_seconds', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('locked', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['plan_versions.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_versions_deleted_at'), 'plan_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_plan_versions_owner_id'), 'plan_versions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_plan_versions_region_id'), 'plan_versions', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_versions_region_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_owner_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_deleted_at'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_saved_days_region_key'), table_name='saved_days')
    op.drop_index(op.f('ix_saved_days_owner_id'), table_name='saved_days')
    op.drop_index(op.f('ix_saved_days_deleted_at'), table_name='saved_days')
    op.drop_table('saved_days')
    op.drop_index(op.f('ix_regions_owner_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_key'), table_name='regions')
    op.drop_index(op.f('ix_regions_deleted_at'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_geo_points_owner_id'), table_name='geo_points')
    op.drop_index(op.f('ix_geo_points_deleted_at'), table_name='geo_points')
    op.drop_index(op.f('ix_geo_points_address_key'), table_name='geo_points')
    op.drop_table('geo_points')
    # ### end Alembic commands ###
